INMAKESWEBAPP/inmakeswebappdjpy/movie/movie/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                    document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL,
                    document_root=settings.MEDIA_ROOT)

INMAKESWEBAPP/inmakeswebappdjpy/movie/movieapp/urls.py
from . import views
from django.urls import path
app_name='movieapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('movi/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add,name='add'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
    
]

INMAKESWEBAPP/inmakeswebappdjpy/movie/movieapp/models.py
from django.db import models

class movie(models.Model):
    name=models.CharField(max_length=120)
    desc=models.TextField()
    year=models.IntegerField()
    imag=models.ImageField(upload_to='gal')
    def __str__(self):
        return self.name
    
    

INMAKESWEBAPP/inmakeswebappdjpy/movie/movieapp/forms.py
from django import forms
from .models import movie
class movieform(forms.ModelForm):
    class Meta:
        model=movie
        fields=['name','desc','imag','year']

INMAKESWEBAPP/inmakeswebappdjpy/movie/movieapp/views.py
from django.shortcuts import render,redirect
from . models import movie
from .forms import movieform


# Create your views here.
def index(request):
    moviee=movie.objects.all()
    return render(request,'index.html',{'mv':moviee})
    
def detail(request,movie_id):
    moviee=movie.objects.get(id=movie_id)
    return render(request,'detail.html',{'moviee':moviee})
    
def add(request):
    if request.method=='POST':
        name=request.POST.get('name',)
        year=request.POST.get('year',)
        desc=request.POST.get('desc',)
        img=request.FILES['imag']
        moviee=movie(name=name,year=year,desc=desc,imag=img)
        moviee.save()
        
    return render(request,'add.html')
    
    
def update(request,id):
    moviee=movie.objects.get(id=id)
    form=movieform(request.POST or None,request.FILES,instance=moviee )
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'moviee':moviee})

def delete(request,id):
    if request.method=='POST':
        moviee=movie.objects.get(id=id)
        moviee.delete()
        return redirect('/')
    return render(request,'delete.html')
    

INMAKESWEBAPP/inmakeswebappdjpy/movie/templates/add.html
{% extends 'base.html' %}
<body>
    {% block body%}
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
<label> Name </label>
<input type="text" name="name" placeholder= "name of the movie" size="15" required /><br>
<label> year: </label>
<input type="text" name="year" placeholder="year of the movie" size="15" required /><br>
<label> description </label>
<input type="text" name="desc" placeholder="plot of the movie" size="15"required /><br>
<input type="file" name="imag"><br>



<button type="submit" class="registerbtn">submit</button>
</form>
{% endblock %}
</body>
</html>

 

INMAKESWEBAPP/inmakeswebappdjpy/movie/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>movie list</title>
</head>
<body>
    <nav class="navbar sticky-top navbar-light bg-dark">
        <a class="navbar-brand" ><h1>movie list</h1><br></a>
      </nav>
    {% block body %}
    {% endblock %}
        
        
</body>
</html>

INMAKESWEBAPP/inmakeswebappdjpy/movie/templates/delete.html
<form method="post">
    {% csrf_token %}
    are yousure want to delete?
    <input type="submit">
</form>

INMAKESWEBAPP/inmakeswebappdjpy/movie/templates/detail.html
{% extends 'base.html' %}
<body>
{% block body %}
        
        <img src="{{moviee.imag.url}}" width="100px" height="100px"><br>
        {{moviee.name}}<br>
        {{moviee.desc}}<br>
        {{moviee.year}}<br>
        <button type="submit" class="registerbtn"><a href={% url 'movieapp:update' moviee.id %}>update</a></button>
        <button type="submit" class="registerbtn"><a href={% url 'movieapp:delete' moviee.id %}>delete</a></button>

        {% endblock %}
</body>
</html>

INMAKESWEBAPP/inmakeswebappdjpy/movie/templates/edit.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

INMAKESWEBAPP/inmakeswebappdjpy/movie/templates/index.html
{% extends 'base.html' %}
<body>
    {% block body %}
    
    
        
        <div class="row">
            {% for i in mv %}
            <div class="col-sm-3">
                <img class="img-responsive" alt="image not found" src="{{i.imag.url}}" width="250px" height="180px"><br>
                <a href=" {% url 'movieapp:detail' i.id %}">{{i.name}}</a><br><br>
            </div>
            {% endfor %}
        </div>

        <button type="submit" class="registerbtn"><a href="add">add movie</button>
        {% endblock  %}
</body>
</html>